### ISSUE TITLE
running and error state?

### ISSUE THREAD

**Issue by aus70** [jschomay/elixir-behavior-tree#6]
Hi Jeff,
do you have any plan to add the _running_ and _error_ states? 
Thanks!

**Comment by jschomay** [comment]
Hi. I do not, but I would welcome a pull request. How would you use that? I
wasn't sure if that made sense in this functional approach. Essentially the
current root node of the zipper tree is "running"

**Comment by aus70** [comment]
You've got a point there. I removed a warning and updated the deps: I'll do a PR in a few mins.

**Comment by jschomay** [comment]
Thanks!  I'll check it out and if you come up with an idea of what running or error would mean in this context, feel free to do another PR :)
